name = "web3-university-worker"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "web3-university-db"
database_id = "9ba2d1e4-a539-43a4-b7a3-3fc8b42ef1db"

[vars]
# Public vars (non-sensitive). Sensitive values use: wrangler secret put
COURSE_MARKET_ADDRESS = "0x6Fc7a078C8d18CF9b339c4509926D9d9eAd5ed61"
SEPOLIA_RPC_URL = "https://ethereum-sepolia-rpc.publicnode.com"
